module.exports = {
  GRAPH_ENDPOINT: process.env.GRAPH_ENDPOINT,
  DATA_API_ENDPOINT: process.env.DATA_API_ENDPOINT,
  NLP_ENDPOINT: process.env.NLP_ENDPOINT,
  NLP_CONFIG_ARANGO: process.env.NLP_CONFIG_ARANGO,
  JWT_SECRET: process.env.JWT_SECRET,
  AWS_S3_BUCKET: process.env.AWS_S3_BUCKET,
  AWS_ACCESS_KEY: process.env.AWS_ACCESS_KEY,
  AWS_SECRET_KEY: process.env.AWS_SECRET_KEY,
  AWS_REGION: process.env.AWS_REGION,
};
